import { defaultConfig } from './config.js';
export { defaultConfig, resolveCourseRoot } from './config.js';
export { loadConfigFromFile } from './config/load-config.js';
export type { ClassifierProvider, ClassificationInput } from './classifier/provider.js';
export { createStubClassifierProvider } from './classifier/stub-provider.js';
export { resolveRuntimeClassifierConfig, createRuntimeClassifierProvider, classifyWithRuntimeFallback } from './classifier/runtime.js';
export { validateClassification } from './classifier/validate-classification.js';
export { parseOpenAIResponsesOutput } from './classifier/parse-openai-responses-output.js';
export type { ResponsesClassifierConfig, ResponsesClient, ResponsesRequest } from './classifier/responses-adapter.js';
export { buildResponsesRequest, createResponsesClassifierProvider } from './classifier/responses-adapter.js';
export { createMockResponsesClient } from './classifier/mock-responses-client.js';
export { createResponsesHttpClient, parseResponsesClassificationResponse } from './classifier/responses-http-client.js';
export type { ProfessorCommand, ParsedProfessorCommand } from './commands/parse-professor-command.js';
export { parseProfessorCommand } from './commands/parse-professor-command.js';
export { executeProfessorCommand } from './commands/execute-professor-command.js';
export { executeApprovedSend } from './commands/execute-professor-send.js';
export { runRuntimeApproveSend } from './commands/runtime-approve-send.js';
export { runRuntimeDraft } from './commands/runtime-draft-send.js';
export { inspectSuperTAState } from './commands/inspect-state.js';
export { listReviewItemsCommand } from './commands/list-review-items.js';
export { getReviewItemCommand } from './commands/get-review-item.js';
export { listOutboundActionsCommand } from './commands/list-outbound-actions.js';
export { listExpiringMailboxesCommand } from './commands/list-expiring-mailboxes.js';
export { initSuperTAConfig } from './setup/init-config.js';
export { addCourseToConfig } from './setup/add-course.js';
export { validateSuperTASetup } from './setup/validate-setup.js';
export { listConfiguredCourses } from './setup/list-courses.js';
export { runSuperTADoctor } from './setup/doctor.js';
export { formatDoctorReport } from './setup/doctor-report.js';
export { runRenewWatchesCommand } from './setup/renew-watches.js';
export { formatRenewWatchesReport } from './setup/renew-watches-report.js';
export { bootstrapThreeCourses } from './setup/bootstrap-three-courses.js';
export { runInteractiveSetup, runInteractiveSetupWithAnswers } from './setup/interactive-setup.js';
export { reviewStoredProposal } from './commands/review-proposal-command.js';
export { resolveGmailAuthConfig, assertGmailAuthConfig } from './gmail/auth-config.js';
export { refreshGmailAccessToken } from './gmail/refresh-token.js';
export { createMockGmailClient } from './gmail/client.js';
export { extractEmailAddress, resolveSelfAddresses, isSelfAddress, normalizeReplySubject, filterReplyRecipients } from './gmail/reply-helpers.js';
export { createGmailHttpClient } from './gmail/http-client.js';
export { createMockGmailHistoryClient } from './gmail/history-client.js';
export { createGmailWatchClient } from './gmail/watch-client.js';
export { registerGmailWatch } from './gmail/register-watch.js';
export { shouldRenewGmailWatch, renewExpiringGmailWatches } from './gmail/renew-watch.js';
export { extractFetchTargetsFromHistory } from './gmail/history-to-fetch.js';
export { deriveFetchTargetsFromWebhook } from './gmail/webhook-to-fetch.js';
export { ingestGmailEvent } from './gmail/ingest.js';
export { normalizeThread } from './gmail/normalize.js';
export { normalizeGmailThread } from './gmail/thread-to-normalized.js';
export { fetchAndProcessThreadTarget } from './gmail/fetch-and-process.js';
export { processWebhookEventIntoPipeline } from './gmail/webhook-to-pipeline.js';
export { runLiveInboundThread } from './gmail/live-inbound-runner.js';
export { parseGmailWebhookEnvelope } from './gmail/webhook.js';
export { handleGmailWebhookBody } from './gmail/webhook-handler.js';
export { draftFromReviewItem, sendApprovedReviewItem, forwardReviewThread, labelReviewThread } from './gmail/executor.js';
export { registerGmailWebhookRoute } from './plugin/register-gmail-webhook.js';
export { default as supertaPlugin } from './plugin/index.js';
export { resolveCourseRoute } from './routing/course-resolver.js';
export { classifyMessage } from './routing/classify.js';
export { applyPolicy } from './routing/policy-engine.js';
export { buildEvidenceBundle } from './retrieval/build-evidence-bundle.js';
export { loadCourseFiles } from './retrieval/load-course-files.js';
export { retrieveCourseFacts } from './retrieval/retrieve-course-facts.js';
export { createReviewQueueItem, updateReviewStatus } from './actions/review-queue.js';
export { executeReviewAction } from './actions/action-executor.js';
export type { ProposalRecord } from './proposals/types.js';
export { createProposal } from './proposals/create-proposal.js';
export { updateProposalStatus } from './proposals/review-proposal.js';
export { applyProposalToCourseFiles } from './proposals/apply-proposal.js';
export { runDeadlineEmailWorkflow } from './demo/deadline-workflow.js';
export { processInboundThread } from './orchestration/process-inbound-thread.js';
export { processInboundThreadWithConfig } from './orchestration/process-with-config.js';
export { processInboundThreadAndStore } from './orchestration/process-and-store.js';
export { processInboundThreadWithClassifier } from './orchestration/process-with-classifier.js';
export { processProfessorCommand } from './orchestration/process-professor-command.js';
export type { PipelineAuditRecord } from './audit/schemas.js';
export { logAudit } from './audit/logger.js';
export { draftReply } from './drafting/draft-reply.js';
export { createDraftEmail } from './tools/draft-email.js';
export type { SuperTAStore } from './storage/store.js';
export { createFileStore, defaultFileStorePaths } from './storage/file-store.js';

export function pluginEntry() {
  return {
    name: 'superta',
    status: 'scaffold',
    config: defaultConfig,
  };
}
