import { runConfigTests } from './config.test.js';
import { runLoadConfigTests } from './load-config.test.js';
import { runRoutingTests } from './routing.test.js';
import { runClassificationContractTests } from './classify.test.js';
import { runPolicyEngineTests } from './policy-engine.test.js';
import { runLoadCourseFilesTests } from './load-course-files.test.js';
import { runRetrieveCourseFactsTests } from './retrieve-course-facts.test.js';
import { runDraftReplyTests } from './draft-reply.test.js';
import { runReviewQueueTests } from './review-queue.test.js';
import { runActionExecutorTests } from './action-executor.test.js';
import { runGmailAuthConfigTests } from './gmail-auth-config.test.js';
import { runGmailRefreshTokenTests } from './gmail-refresh-token.test.js';
import { runGmailClientTests } from './gmail-client.test.js';
import { runGmailHttpClientTests } from './gmail-http-client.test.js';
import { runGmailExecutorTests } from './gmail-executor.test.js';
import { runGmailWebhookTests } from './gmail-webhook.test.js';
import { runRegisterGmailWebhookTests } from './register-gmail-webhook.test.js';
import { runGmailWatchClientTests } from './gmail-watch-client.test.js';
import { runGmailRenewWatchTests } from './gmail-renew-watch.test.js';
import { runGmailHistoryTests } from './gmail-history.test.js';
import { runThreadToNormalizedTests } from './thread-to-normalized.test.js';
import { runFetchAndProcessTests } from './fetch-and-process.test.js';
import { runWebhookToPipelineTests } from './webhook-to-pipeline.test.js';
import { runAuditLoggerTests } from './audit-logger.test.js';
import { runFileStoreTests } from './file-store.test.js';
import { runStubClassifierTests } from './stub-classifier.test.js';
import { runValidateClassificationTests } from './validate-classification.test.js';
import { runParseOpenAIResponsesOutputTests } from './parse-openai-responses-output.test.js';
import { runResponsesAdapterTests } from './responses-adapter.test.js';
import { runResponsesHttpClientTests } from './responses-http-client.test.js';
import { runProposalTests } from './proposals.test.js';
import { runProfessorCommandParserTests } from './parse-professor-command.test.js';
import { runProcessProfessorCommandTests } from './process-professor-command.test.js';
import { runExecuteProfessorCommandTests } from './execute-professor-command.test.js';
import { runExecuteProfessorSendTests } from './execute-professor-send.test.js';
import { runProposalReviewAndApplyTests } from './proposal-review-and-apply.test.js';
import { runDeadlineWorkflowTests } from './deadline-workflow.test.js';
import { runProcessInboundThreadTests } from './process-inbound-thread.test.js';
import { runProcessWithConfigTests } from './process-with-config.test.js';
import { runProcessAndStoreTests } from './process-and-store.test.js';
import { runProcessWithClassifierTests } from './process-with-classifier.test.js';
import { runLiveInboundRunnerTests } from './live-inbound-runner.test.js';

async function main() {
  runConfigTests();
  await runLoadConfigTests();
  runRoutingTests();
  runClassificationContractTests();
  runPolicyEngineTests();
  await runLoadCourseFilesTests();
  await runRetrieveCourseFactsTests();
  runDraftReplyTests();
  runReviewQueueTests();
  runActionExecutorTests();
  runGmailAuthConfigTests();
  await runGmailRefreshTokenTests();
  await runGmailClientTests();
  await runGmailHttpClientTests();
  await runGmailExecutorTests();
  await runGmailWebhookTests();
  await runRegisterGmailWebhookTests();
  await runGmailWatchClientTests();
  await runGmailRenewWatchTests();
  await runGmailHistoryTests();
  runThreadToNormalizedTests();
  await runFetchAndProcessTests();
  await runWebhookToPipelineTests();
  runAuditLoggerTests();
  await runFileStoreTests();
  await runStubClassifierTests();
  runValidateClassificationTests();
  runParseOpenAIResponsesOutputTests();
  await runResponsesAdapterTests();
  await runResponsesHttpClientTests();
  runProposalTests();
  runProfessorCommandParserTests();
  runProcessProfessorCommandTests();
  await runExecuteProfessorCommandTests();
  await runExecuteProfessorSendTests();
  await runProposalReviewAndApplyTests();
  await runDeadlineWorkflowTests();
  await runProcessInboundThreadTests();
  await runProcessWithConfigTests();
  await runProcessAndStoreTests();
  await runProcessWithClassifierTests();
  await runLiveInboundRunnerTests();
  console.log('plugin tests passed');
}

await main();
